
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['ground-api-gateway:8000']

  - job_name: 'ingest-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['ground-ingest-service:8001']

  - job_name: 'telemetry-processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['ground-telemetry-processor:8002']

